local p = require 'themes.omtheme.palette'

local M = {}

function M.set_groups()
  local set = vim.api.nvim_set_hl

  set(0, 'Normal', { fg = p.gray_5, bg = p.bg })
  set(0, 'NormalNC', { fg = p.gray_5, bg = p.bg })
  set(0, 'NormalFloat', { fg = p.gray_5, bg = p.bg_float })
  set(0, 'FloatBorder', { fg = p.teal, bg = p.bg_float })
  set(0, 'FloatTitle', { fg = p.teal, bg = p.bg_float, bold = true })
  set(0, 'Cursor', { fg = p.bg, bg = p.gray_5 })
  set(0, 'CursorLine', { bg = p.bg_highlight })
  set(0, 'CursorLineNr', { fg = p.magenta, bold = true })
  set(0, 'LineNr', { fg = p.comment })
  set(0, 'SignColumn', { fg = p.comment, bg = p.bg })
  set(0, 'StatusLine', { fg = p.gray_6, bg = p.black })
  set(0, 'StatusLineNC', { fg = p.gray_2, bg = p.black })
  set(0, 'WinSeparator', { fg = p.border })
  set(0, 'Visual', { bg = p.bg_highlight })
  set(0, 'Search', { fg = p.gray_6, bg = p.blue_dark })
  set(0, 'IncSearch', { fg = p.black, bg = p.orange })
  set(0, 'Pmenu', { fg = p.gray_5, bg = p.black })
  set(0, 'PmenuSel', { fg = p.gray_6, bg = p.bg_highlight })
  set(0, 'PmenuSbar', { bg = p.black })
  set(0, 'PmenuThumb', { bg = p.gray_2 })
  set(0, 'Folded', { fg = p.blue, bg = p.bg_alt })
  set(0, 'ColorColumn', { bg = p.bg_highlight })
  set(0, 'Whitespace', { fg = p.gray_1 })
  set(0, 'NonText', { fg = p.gray_1 })
  set(0, 'EndOfBuffer', { fg = p.bg })

  set(0, 'Comment', { fg = p.comment, italic = true })
  set(0, 'Constant', { fg = p.orange })
  set(0, 'String', { fg = p.green })
  set(0, 'Character', { fg = p.green })
  set(0, 'Number', { fg = p.orange })
  set(0, 'Boolean', { fg = p.orange })
  set(0, 'Identifier', { fg = p.blue })
  set(0, 'Function', { fg = p.blue })
  set(0, 'Statement', { fg = p.magenta })
  set(0, 'Conditional', { fg = p.magenta, italic = true })
  set(0, 'Repeat', { fg = p.magenta, italic = true })
  set(0, 'Keyword', { fg = p.cyan, italic = true })
  set(0, 'Operator', { fg = p.cyan })
  set(0, 'PreProc', { fg = p.cyan })
  set(0, 'Type', { fg = p.blue })
  set(0, 'Special', { fg = p.purple })
  set(0, 'Title', { fg = p.blue, bold = true })
  set(0, 'Directory', { fg = p.blue })
  set(0, 'Underlined', { underline = true })

  set(0, 'DiagnosticError', { fg = p.red })
  set(0, 'DiagnosticWarn', { fg = p.yellow })
  set(0, 'DiagnosticInfo', { fg = p.blue })
  set(0, 'DiagnosticHint', { fg = p.cyan })
  set(0, 'DiagnosticOk', { fg = p.green })
  set(0, 'DiagnosticUnderlineError', { undercurl = true, sp = p.red })
  set(0, 'DiagnosticUnderlineWarn', { undercurl = true, sp = p.yellow })
  set(0, 'DiagnosticUnderlineInfo', { undercurl = true, sp = p.blue })
  set(0, 'DiagnosticUnderlineHint', { undercurl = true, sp = p.cyan })

  set(0, 'SpellBad', { sp = p.gray_3, underdashed = true })
  set(0, 'SpellCap', { sp = p.yellow, undercurl = true })
  set(0, 'SpellLocal', { sp = p.blue, undercurl = true })
  set(0, 'SpellRare', { sp = p.purple, undercurl = true })

  set(0, 'TelescopeNormal', { fg = p.gray_5, bg = p.black })
  set(0, 'TelescopeBorder', { fg = p.comment, bg = p.black })
  set(0, 'TelescopePromptBorder', { fg = p.comment, bg = p.black })
  set(0, 'TelescopePromptTitle', { fg = p.gray_5, bg = p.black })
  set(0, 'TelescopeResultsComment', { fg = p.comment })
end

return M
